### PR TITLE
Feature: Support OAuth for the Tailscale API

### PR DESCRIPTION
**Pull request by offbyone**
Introduces the client ID and client secret paramters, which add an OAuth
client option. It augments the local API client and the public API JSON
client, but doesn't require a relatively shortlived API token

### CODE REVIEW

**Comment by cfunkhouser** [comment]
Looks reasonable to me. Please also include the added flags / env vars to the README.

**Comment by offbyone** [comment]
Done.

**Review by cfunkhouser — APPROVED** [review]

**Comment by offbyone** [comment]
This'll require the merge of #17 before it can build successfully.

**Comment by cfunkhouser** [comment]
I took the liberty of merging that and rebasing this branch. Feel free to merge at your leisure.

Thanks!

**Comment by offbyone** [comment]
I don't have write permissions, so I won't be able to merge it :D

**Comment by offbyone** [comment]
No worries! I appreciate the review, the package, and the merge :D

**Pull request merged**
